"""empty message

Revision ID: fe179501f99f
Revises: 
Create Date: 2021-10-06 14:51:36.564389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe179501f99f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_migration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=38), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_migration')
    # ### end Alembic commands ###
